word = str(input())
lenght = len(word)
print(word[2])
print(word[lenght-2])
print(word[:5])
print(word[:-2])
print(word[::2])
print(word[1::2])
print(word[::-1])
print(word[::-2])
print(lenght)